
language: python

sudo: required
dist: trusty

addons:
  postgresq: "9.4"

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief
    - HTTPD_ERROR_LOG=/var/log/apache2/error.log

before_install:
  - sudo apt-get -y update
  - sudo service postgresql stop
  - sudo apt-get -y purge postgresql-9.1 postgresql-9.2 postgresql-9.3
  - sudo service postgresql start 9.4
  - sudo apt-get -y install libpq-dev postgresql-server-dev-9.4 python-dev
  - sudo apt-get -y install apache2 apache2-dev libjson-c-dev ssl-cert libapache2-mod-wsgi python python-dateutil python-tz
  - sudo apt-get -y purge python-psycopg2
  - sudo pip install web.py
  - sudo pip install psycopg2
  - sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl

install:
  - sudo make testvars
  - sudo make install
  - sudo make deploy
  - sudo bash ./test/static-test-setup.sh
  - sudo a2enmod webauthn
  - sudo service apache2 restart
  - sudo ls -lR /etc/apache2
  - sudo ls -lR /var/run/apache2
  - sudo ls -lR /var/log/apache2

script:
  - sudo -H -u webauthn webauthn2-manage adduser test1
  - sudo -H -u webauthn webauthn2-manage passwd test1 dummypassword1
  - sudo -H -u webauthn webauthn2-manage addattr admin
  - sudo -H -u webauthn webauthn2-manage assign test1 admin
  - sudo -H -u webauthn webauthn2-manage adduser test2
  - sudo -H -u webauthn webauthn2-manage passwd test2 dummypassword2
  - sudo bash ./test/rest-tests.sh test1 dummypassword1
  - sudo bash ./test/static-tests.sh test1 dummypassword1

after_failure:
  - sudo cat /etc/apache2/conf.d/wsgi_webauthn2.conf
  - sudo cat /etc/apache2/conf.d/webauthn_test.conf
  - sudo cat /etc/apache2/mods-available/webauthn.load
  - sudo cat /etc/apache2/apache2.conf
  - sudo cat /etc/apache2/sites-available/default-ssl.conf
  - sudo ls -lR /etc/apache2
  - sudo cat ${HTTPD_ERROR_LOG}
  - sudo cat /var/log/apache2/access.log
