
language: python

sudo: required
dist: xenial

python:
  - "3.5"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - libpq-dev
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
      - apache2
      - apache2-dev
      - ssl-cert
      - libapache2-mod-wsgi-py3
      - python3-pip

env:
  global:
    - COOKIES=~/cookies
    - VERBOSE=brief
    - HTTPD_ERROR_LOG=/var/log/apache2/error.log
    - PYTHONWARNINGS="ignore:Unverified HTTPS request"
    - PGPORT=5433

before_install:
  - sudo ln -s /etc/apache2/conf-enabled /etc/apache2/conf.d
  - sudo a2enmod ssl
  - sudo a2ensite default-ssl
  - sudo groupadd -o -g $(id -g www-data) apache

install:
  - sudo ls -lR /etc/apache2
  - sudo cat /etc/apache2/envvars
  - sudo make testvars
  - sudo ls -l /usr/bin/python*
  - sudo ls -l /usr/bin/pip*
  - sudo head -1 /usr/bin/pip3
  - sudo make install
  - sudo make deploy
  - sudo bash ./test/ubuntu-travis-setup.sh
  - sudo bash ./test/static-test-setup.sh
  - sudo a2enmod webauthn
  - sudo service apache2 restart
  - sudo ls -lR /var/run/apache2
  - sudo ls -lR /var/log/apache2

script:
  - sudo -H -u webauthn webauthn2-manage adduser test1
  - sudo -H -u webauthn webauthn2-manage passwd test1 dummypassword1
  - sudo -H -u webauthn webauthn2-manage addattr admin
  - sudo -H -u webauthn webauthn2-manage assign test1 admin
  - sudo -H -u webauthn webauthn2-manage adduser test2
  - sudo -H -u webauthn webauthn2-manage passwd test2 dummypassword2
  - sudo bash ./test/rest-tests.sh test1 dummypassword1
  - sudo bash ./test/static-tests.sh test1 dummypassword1
  - sudo -H -u webauthn webauthn2-manage addrobot robot123 /tmp/robot123cred.json 5
  - sudo bash ./test/robot-cred-test.sh /tmp/robot123cred.json

after_failure:
  - sudo cat /etc/apache2/conf.d/webauthn.conf
  - sudo cat /etc/apache2/conf.d/wsgi_webauthn2.conf
  - sudo cat /etc/apache2/conf.d/webauthn_test.conf
  - sudo cat /etc/apache2/mods-available/webauthn.load
  - sudo cat /etc/hosts
  - sudo cat /etc/apache2/apache2.conf
  - sudo cat /etc/apache2/sites-available/default-ssl.conf
  - sudo ls -lR /etc/apache2
  - sudo cat ${HTTPD_ERROR_LOG}
  - sudo cat /var/log/apache2/access.log
  - sudo cat /tmp/robot123cred.json
